/*
 * This file is generated by jOOQ.
 */
package com.cardealership.cardealership.models;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import java.io.Serializable;

@Entity
@Table(name = "brands", schema = "car_dealership")
public class Brands extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Column(name = "name")
    private String name;

    public Brands() {}

    public Brands(String name) {
        this.name = name;
    }

    public Brands(Brands value) {
        this.name = value.name;
    }

    /**
     * Getter for <code>car_dealership.brands.brand_id</code>.
     */


    /**
     * Getter for <code>car_dealership.brands.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>car_dealership.brands.name</code>.
     */
    public Brands setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Brands other = (Brands) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "Brands [id=" + getId() + ", name=" + name + "]";
    }
}
