/*
 * This file is generated by jOOQ.
 */
package com.cardealership.cardealership.models;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CustomerAddresses implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long addressId;
    private Long customerId;
    private String addressType;
    private String line1;
    private String line2;
    private String city;
    private String state;
    private String postalCode;
    private String country;
    private Boolean isPrimary;

    public CustomerAddresses() {}

    public CustomerAddresses(CustomerAddresses value) {
        this.addressId = value.addressId;
        this.customerId = value.customerId;
        this.addressType = value.addressType;
        this.line1 = value.line1;
        this.line2 = value.line2;
        this.city = value.city;
        this.state = value.state;
        this.postalCode = value.postalCode;
        this.country = value.country;
        this.isPrimary = value.isPrimary;
    }

    public CustomerAddresses(
        Long addressId,
        Long customerId,
        String addressType,
        String line1,
        String line2,
        String city,
        String state,
        String postalCode,
        String country,
        Boolean isPrimary
    ) {
        this.addressId = addressId;
        this.customerId = customerId;
        this.addressType = addressType;
        this.line1 = line1;
        this.line2 = line2;
        this.city = city;
        this.state = state;
        this.postalCode = postalCode;
        this.country = country;
        this.isPrimary = isPrimary;
    }

    /**
     * Getter for <code>car_dealership.customer_addresses.address_id</code>.
     */
    public Long getAddressId() {
        return this.addressId;
    }

    /**
     * Setter for <code>car_dealership.customer_addresses.address_id</code>.
     */
    public CustomerAddresses setAddressId(Long addressId) {
        this.addressId = addressId;
        return this;
    }

    /**
     * Getter for <code>car_dealership.customer_addresses.customer_id</code>.
     */
    public Long getCustomerId() {
        return this.customerId;
    }

    /**
     * Setter for <code>car_dealership.customer_addresses.customer_id</code>.
     */
    public CustomerAddresses setCustomerId(Long customerId) {
        this.customerId = customerId;
        return this;
    }

    /**
     * Getter for <code>car_dealership.customer_addresses.address_type</code>.
     */
    public String getAddressType() {
        return this.addressType;
    }

    /**
     * Setter for <code>car_dealership.customer_addresses.address_type</code>.
     */
    public CustomerAddresses setAddressType(String addressType) {
        this.addressType = addressType;
        return this;
    }

    /**
     * Getter for <code>car_dealership.customer_addresses.line1</code>.
     */
    public String getLine1() {
        return this.line1;
    }

    /**
     * Setter for <code>car_dealership.customer_addresses.line1</code>.
     */
    public CustomerAddresses setLine1(String line1) {
        this.line1 = line1;
        return this;
    }

    /**
     * Getter for <code>car_dealership.customer_addresses.line2</code>.
     */
    public String getLine2() {
        return this.line2;
    }

    /**
     * Setter for <code>car_dealership.customer_addresses.line2</code>.
     */
    public CustomerAddresses setLine2(String line2) {
        this.line2 = line2;
        return this;
    }

    /**
     * Getter for <code>car_dealership.customer_addresses.city</code>.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>car_dealership.customer_addresses.city</code>.
     */
    public CustomerAddresses setCity(String city) {
        this.city = city;
        return this;
    }

    /**
     * Getter for <code>car_dealership.customer_addresses.state</code>.
     */
    public String getState() {
        return this.state;
    }

    /**
     * Setter for <code>car_dealership.customer_addresses.state</code>.
     */
    public CustomerAddresses setState(String state) {
        this.state = state;
        return this;
    }

    /**
     * Getter for <code>car_dealership.customer_addresses.postal_code</code>.
     */
    public String getPostalCode() {
        return this.postalCode;
    }

    /**
     * Setter for <code>car_dealership.customer_addresses.postal_code</code>.
     */
    public CustomerAddresses setPostalCode(String postalCode) {
        this.postalCode = postalCode;
        return this;
    }

    /**
     * Getter for <code>car_dealership.customer_addresses.country</code>.
     */
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>car_dealership.customer_addresses.country</code>.
     */
    public CustomerAddresses setCountry(String country) {
        this.country = country;
        return this;
    }

    /**
     * Getter for <code>car_dealership.customer_addresses.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return this.isPrimary;
    }

    /**
     * Setter for <code>car_dealership.customer_addresses.is_primary</code>.
     */
    public CustomerAddresses setIsPrimary(Boolean isPrimary) {
        this.isPrimary = isPrimary;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CustomerAddresses other = (CustomerAddresses) obj;
        if (this.addressId == null) {
            if (other.addressId != null)
                return false;
        }
        else if (!this.addressId.equals(other.addressId))
            return false;
        if (this.customerId == null) {
            if (other.customerId != null)
                return false;
        }
        else if (!this.customerId.equals(other.customerId))
            return false;
        if (this.addressType == null) {
            if (other.addressType != null)
                return false;
        }
        else if (!this.addressType.equals(other.addressType))
            return false;
        if (this.line1 == null) {
            if (other.line1 != null)
                return false;
        }
        else if (!this.line1.equals(other.line1))
            return false;
        if (this.line2 == null) {
            if (other.line2 != null)
                return false;
        }
        else if (!this.line2.equals(other.line2))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        if (this.postalCode == null) {
            if (other.postalCode != null)
                return false;
        }
        else if (!this.postalCode.equals(other.postalCode))
            return false;
        if (this.country == null) {
            if (other.country != null)
                return false;
        }
        else if (!this.country.equals(other.country))
            return false;
        if (this.isPrimary == null) {
            if (other.isPrimary != null)
                return false;
        }
        else if (!this.isPrimary.equals(other.isPrimary))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.addressId == null) ? 0 : this.addressId.hashCode());
        result = prime * result + ((this.customerId == null) ? 0 : this.customerId.hashCode());
        result = prime * result + ((this.addressType == null) ? 0 : this.addressType.hashCode());
        result = prime * result + ((this.line1 == null) ? 0 : this.line1.hashCode());
        result = prime * result + ((this.line2 == null) ? 0 : this.line2.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        result = prime * result + ((this.postalCode == null) ? 0 : this.postalCode.hashCode());
        result = prime * result + ((this.country == null) ? 0 : this.country.hashCode());
        result = prime * result + ((this.isPrimary == null) ? 0 : this.isPrimary.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustomerAddresses (");

        sb.append(addressId);
        sb.append(", ").append(customerId);
        sb.append(", ").append(addressType);
        sb.append(", ").append(line1);
        sb.append(", ").append(line2);
        sb.append(", ").append(city);
        sb.append(", ").append(state);
        sb.append(", ").append(postalCode);
        sb.append(", ").append(country);
        sb.append(", ").append(isPrimary);

        sb.append(")");
        return sb.toString();
    }
}
