/*
 * This file is generated by jOOQ.
 */
package com.cardealership.cardealership.models;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FinancingApplications implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long financingId;
    private Long salesOrderId;
    private Long lenderId;
    private String status;
    private BigDecimal requestedAmount;
    private BigDecimal approvedAmount;
    private BigDecimal annualRatePct;
    private Integer termMonths;
    private BigDecimal estimatedMonthly;

    public FinancingApplications() {}

    public FinancingApplications(FinancingApplications value) {
        this.financingId = value.financingId;
        this.salesOrderId = value.salesOrderId;
        this.lenderId = value.lenderId;
        this.status = value.status;
        this.requestedAmount = value.requestedAmount;
        this.approvedAmount = value.approvedAmount;
        this.annualRatePct = value.annualRatePct;
        this.termMonths = value.termMonths;
        this.estimatedMonthly = value.estimatedMonthly;
    }

    public FinancingApplications(
        Long financingId,
        Long salesOrderId,
        Long lenderId,
        String status,
        BigDecimal requestedAmount,
        BigDecimal approvedAmount,
        BigDecimal annualRatePct,
        Integer termMonths,
        BigDecimal estimatedMonthly
    ) {
        this.financingId = financingId;
        this.salesOrderId = salesOrderId;
        this.lenderId = lenderId;
        this.status = status;
        this.requestedAmount = requestedAmount;
        this.approvedAmount = approvedAmount;
        this.annualRatePct = annualRatePct;
        this.termMonths = termMonths;
        this.estimatedMonthly = estimatedMonthly;
    }

    /**
     * Getter for
     * <code>car_dealership.financing_applications.financing_id</code>.
     */
    public Long getFinancingId() {
        return this.financingId;
    }

    /**
     * Setter for
     * <code>car_dealership.financing_applications.financing_id</code>.
     */
    public FinancingApplications setFinancingId(Long financingId) {
        this.financingId = financingId;
        return this;
    }

    /**
     * Getter for
     * <code>car_dealership.financing_applications.sales_order_id</code>.
     */
    public Long getSalesOrderId() {
        return this.salesOrderId;
    }

    /**
     * Setter for
     * <code>car_dealership.financing_applications.sales_order_id</code>.
     */
    public FinancingApplications setSalesOrderId(Long salesOrderId) {
        this.salesOrderId = salesOrderId;
        return this;
    }

    /**
     * Getter for <code>car_dealership.financing_applications.lender_id</code>.
     */
    public Long getLenderId() {
        return this.lenderId;
    }

    /**
     * Setter for <code>car_dealership.financing_applications.lender_id</code>.
     */
    public FinancingApplications setLenderId(Long lenderId) {
        this.lenderId = lenderId;
        return this;
    }

    /**
     * Getter for <code>car_dealership.financing_applications.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>car_dealership.financing_applications.status</code>.
     */
    public FinancingApplications setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for
     * <code>car_dealership.financing_applications.requested_amount</code>.
     */
    public BigDecimal getRequestedAmount() {
        return this.requestedAmount;
    }

    /**
     * Setter for
     * <code>car_dealership.financing_applications.requested_amount</code>.
     */
    public FinancingApplications setRequestedAmount(BigDecimal requestedAmount) {
        this.requestedAmount = requestedAmount;
        return this;
    }

    /**
     * Getter for
     * <code>car_dealership.financing_applications.approved_amount</code>.
     */
    public BigDecimal getApprovedAmount() {
        return this.approvedAmount;
    }

    /**
     * Setter for
     * <code>car_dealership.financing_applications.approved_amount</code>.
     */
    public FinancingApplications setApprovedAmount(BigDecimal approvedAmount) {
        this.approvedAmount = approvedAmount;
        return this;
    }

    /**
     * Getter for
     * <code>car_dealership.financing_applications.annual_rate_pct</code>.
     */
    public BigDecimal getAnnualRatePct() {
        return this.annualRatePct;
    }

    /**
     * Setter for
     * <code>car_dealership.financing_applications.annual_rate_pct</code>.
     */
    public FinancingApplications setAnnualRatePct(BigDecimal annualRatePct) {
        this.annualRatePct = annualRatePct;
        return this;
    }

    /**
     * Getter for
     * <code>car_dealership.financing_applications.term_months</code>.
     */
    public Integer getTermMonths() {
        return this.termMonths;
    }

    /**
     * Setter for
     * <code>car_dealership.financing_applications.term_months</code>.
     */
    public FinancingApplications setTermMonths(Integer termMonths) {
        this.termMonths = termMonths;
        return this;
    }

    /**
     * Getter for
     * <code>car_dealership.financing_applications.estimated_monthly</code>.
     */
    public BigDecimal getEstimatedMonthly() {
        return this.estimatedMonthly;
    }

    /**
     * Setter for
     * <code>car_dealership.financing_applications.estimated_monthly</code>.
     */
    public FinancingApplications setEstimatedMonthly(BigDecimal estimatedMonthly) {
        this.estimatedMonthly = estimatedMonthly;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FinancingApplications other = (FinancingApplications) obj;
        if (this.financingId == null) {
            if (other.financingId != null)
                return false;
        }
        else if (!this.financingId.equals(other.financingId))
            return false;
        if (this.salesOrderId == null) {
            if (other.salesOrderId != null)
                return false;
        }
        else if (!this.salesOrderId.equals(other.salesOrderId))
            return false;
        if (this.lenderId == null) {
            if (other.lenderId != null)
                return false;
        }
        else if (!this.lenderId.equals(other.lenderId))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.requestedAmount == null) {
            if (other.requestedAmount != null)
                return false;
        }
        else if (!this.requestedAmount.equals(other.requestedAmount))
            return false;
        if (this.approvedAmount == null) {
            if (other.approvedAmount != null)
                return false;
        }
        else if (!this.approvedAmount.equals(other.approvedAmount))
            return false;
        if (this.annualRatePct == null) {
            if (other.annualRatePct != null)
                return false;
        }
        else if (!this.annualRatePct.equals(other.annualRatePct))
            return false;
        if (this.termMonths == null) {
            if (other.termMonths != null)
                return false;
        }
        else if (!this.termMonths.equals(other.termMonths))
            return false;
        if (this.estimatedMonthly == null) {
            if (other.estimatedMonthly != null)
                return false;
        }
        else if (!this.estimatedMonthly.equals(other.estimatedMonthly))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.financingId == null) ? 0 : this.financingId.hashCode());
        result = prime * result + ((this.salesOrderId == null) ? 0 : this.salesOrderId.hashCode());
        result = prime * result + ((this.lenderId == null) ? 0 : this.lenderId.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.requestedAmount == null) ? 0 : this.requestedAmount.hashCode());
        result = prime * result + ((this.approvedAmount == null) ? 0 : this.approvedAmount.hashCode());
        result = prime * result + ((this.annualRatePct == null) ? 0 : this.annualRatePct.hashCode());
        result = prime * result + ((this.termMonths == null) ? 0 : this.termMonths.hashCode());
        result = prime * result + ((this.estimatedMonthly == null) ? 0 : this.estimatedMonthly.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FinancingApplications (");

        sb.append(financingId);
        sb.append(", ").append(salesOrderId);
        sb.append(", ").append(lenderId);
        sb.append(", ").append(status);
        sb.append(", ").append(requestedAmount);
        sb.append(", ").append(approvedAmount);
        sb.append(", ").append(annualRatePct);
        sb.append(", ").append(termMonths);
        sb.append(", ").append(estimatedMonthly);

        sb.append(")");
        return sb.toString();
    }
}
