/*
 * This file is generated by jOOQ.
 */
package com.cardealership.cardealership.models;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InsurancePolicies implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long policyId;
    private Long salesOrderId;
    private String provider;
    private String policyNumber;
    private LocalDate startDate;
    private LocalDate endDate;
    private BigDecimal premiumAmount;

    public InsurancePolicies() {}

    public InsurancePolicies(InsurancePolicies value) {
        this.policyId = value.policyId;
        this.salesOrderId = value.salesOrderId;
        this.provider = value.provider;
        this.policyNumber = value.policyNumber;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
        this.premiumAmount = value.premiumAmount;
    }

    public InsurancePolicies(
        Long policyId,
        Long salesOrderId,
        String provider,
        String policyNumber,
        LocalDate startDate,
        LocalDate endDate,
        BigDecimal premiumAmount
    ) {
        this.policyId = policyId;
        this.salesOrderId = salesOrderId;
        this.provider = provider;
        this.policyNumber = policyNumber;
        this.startDate = startDate;
        this.endDate = endDate;
        this.premiumAmount = premiumAmount;
    }

    /**
     * Getter for <code>car_dealership.insurance_policies.policy_id</code>.
     */
    public Long getPolicyId() {
        return this.policyId;
    }

    /**
     * Setter for <code>car_dealership.insurance_policies.policy_id</code>.
     */
    public InsurancePolicies setPolicyId(Long policyId) {
        this.policyId = policyId;
        return this;
    }

    /**
     * Getter for <code>car_dealership.insurance_policies.sales_order_id</code>.
     */
    public Long getSalesOrderId() {
        return this.salesOrderId;
    }

    /**
     * Setter for <code>car_dealership.insurance_policies.sales_order_id</code>.
     */
    public InsurancePolicies setSalesOrderId(Long salesOrderId) {
        this.salesOrderId = salesOrderId;
        return this;
    }

    /**
     * Getter for <code>car_dealership.insurance_policies.provider</code>.
     */
    public String getProvider() {
        return this.provider;
    }

    /**
     * Setter for <code>car_dealership.insurance_policies.provider</code>.
     */
    public InsurancePolicies setProvider(String provider) {
        this.provider = provider;
        return this;
    }

    /**
     * Getter for <code>car_dealership.insurance_policies.policy_number</code>.
     */
    public String getPolicyNumber() {
        return this.policyNumber;
    }

    /**
     * Setter for <code>car_dealership.insurance_policies.policy_number</code>.
     */
    public InsurancePolicies setPolicyNumber(String policyNumber) {
        this.policyNumber = policyNumber;
        return this;
    }

    /**
     * Getter for <code>car_dealership.insurance_policies.start_date</code>.
     */
    public LocalDate getStartDate() {
        return this.startDate;
    }

    /**
     * Setter for <code>car_dealership.insurance_policies.start_date</code>.
     */
    public InsurancePolicies setStartDate(LocalDate startDate) {
        this.startDate = startDate;
        return this;
    }

    /**
     * Getter for <code>car_dealership.insurance_policies.end_date</code>.
     */
    public LocalDate getEndDate() {
        return this.endDate;
    }

    /**
     * Setter for <code>car_dealership.insurance_policies.end_date</code>.
     */
    public InsurancePolicies setEndDate(LocalDate endDate) {
        this.endDate = endDate;
        return this;
    }

    /**
     * Getter for <code>car_dealership.insurance_policies.premium_amount</code>.
     */
    public BigDecimal getPremiumAmount() {
        return this.premiumAmount;
    }

    /**
     * Setter for <code>car_dealership.insurance_policies.premium_amount</code>.
     */
    public InsurancePolicies setPremiumAmount(BigDecimal premiumAmount) {
        this.premiumAmount = premiumAmount;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final InsurancePolicies other = (InsurancePolicies) obj;
        if (this.policyId == null) {
            if (other.policyId != null)
                return false;
        }
        else if (!this.policyId.equals(other.policyId))
            return false;
        if (this.salesOrderId == null) {
            if (other.salesOrderId != null)
                return false;
        }
        else if (!this.salesOrderId.equals(other.salesOrderId))
            return false;
        if (this.provider == null) {
            if (other.provider != null)
                return false;
        }
        else if (!this.provider.equals(other.provider))
            return false;
        if (this.policyNumber == null) {
            if (other.policyNumber != null)
                return false;
        }
        else if (!this.policyNumber.equals(other.policyNumber))
            return false;
        if (this.startDate == null) {
            if (other.startDate != null)
                return false;
        }
        else if (!this.startDate.equals(other.startDate))
            return false;
        if (this.endDate == null) {
            if (other.endDate != null)
                return false;
        }
        else if (!this.endDate.equals(other.endDate))
            return false;
        if (this.premiumAmount == null) {
            if (other.premiumAmount != null)
                return false;
        }
        else if (!this.premiumAmount.equals(other.premiumAmount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.policyId == null) ? 0 : this.policyId.hashCode());
        result = prime * result + ((this.salesOrderId == null) ? 0 : this.salesOrderId.hashCode());
        result = prime * result + ((this.provider == null) ? 0 : this.provider.hashCode());
        result = prime * result + ((this.policyNumber == null) ? 0 : this.policyNumber.hashCode());
        result = prime * result + ((this.startDate == null) ? 0 : this.startDate.hashCode());
        result = prime * result + ((this.endDate == null) ? 0 : this.endDate.hashCode());
        result = prime * result + ((this.premiumAmount == null) ? 0 : this.premiumAmount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InsurancePolicies (");

        sb.append(policyId);
        sb.append(", ").append(salesOrderId);
        sb.append(", ").append(provider);
        sb.append(", ").append(policyNumber);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);
        sb.append(", ").append(premiumAmount);

        sb.append(")");
        return sb.toString();
    }
}
