/*
 * This file is generated by jOOQ.
 */
package com.cardealership.cardealership.models;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InventoryMovements implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long movementId;
    private Long vehicleId;
    private String movementType;
    private Integer quantity;
    private OffsetDateTime movedAt;
    private String reference;

    public InventoryMovements() {}

    public InventoryMovements(InventoryMovements value) {
        this.movementId = value.movementId;
        this.vehicleId = value.vehicleId;
        this.movementType = value.movementType;
        this.quantity = value.quantity;
        this.movedAt = value.movedAt;
        this.reference = value.reference;
    }

    public InventoryMovements(
        Long movementId,
        Long vehicleId,
        String movementType,
        Integer quantity,
        OffsetDateTime movedAt,
        String reference
    ) {
        this.movementId = movementId;
        this.vehicleId = vehicleId;
        this.movementType = movementType;
        this.quantity = quantity;
        this.movedAt = movedAt;
        this.reference = reference;
    }

    /**
     * Getter for <code>car_dealership.inventory_movements.movement_id</code>.
     */
    public Long getMovementId() {
        return this.movementId;
    }

    /**
     * Setter for <code>car_dealership.inventory_movements.movement_id</code>.
     */
    public InventoryMovements setMovementId(Long movementId) {
        this.movementId = movementId;
        return this;
    }

    /**
     * Getter for <code>car_dealership.inventory_movements.vehicle_id</code>.
     */
    public Long getVehicleId() {
        return this.vehicleId;
    }

    /**
     * Setter for <code>car_dealership.inventory_movements.vehicle_id</code>.
     */
    public InventoryMovements setVehicleId(Long vehicleId) {
        this.vehicleId = vehicleId;
        return this;
    }

    /**
     * Getter for <code>car_dealership.inventory_movements.movement_type</code>.
     */
    public String getMovementType() {
        return this.movementType;
    }

    /**
     * Setter for <code>car_dealership.inventory_movements.movement_type</code>.
     */
    public InventoryMovements setMovementType(String movementType) {
        this.movementType = movementType;
        return this;
    }

    /**
     * Getter for <code>car_dealership.inventory_movements.quantity</code>.
     */
    public Integer getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>car_dealership.inventory_movements.quantity</code>.
     */
    public InventoryMovements setQuantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Getter for <code>car_dealership.inventory_movements.moved_at</code>.
     */
    public OffsetDateTime getMovedAt() {
        return this.movedAt;
    }

    /**
     * Setter for <code>car_dealership.inventory_movements.moved_at</code>.
     */
    public InventoryMovements setMovedAt(OffsetDateTime movedAt) {
        this.movedAt = movedAt;
        return this;
    }

    /**
     * Getter for <code>car_dealership.inventory_movements.reference</code>.
     */
    public String getReference() {
        return this.reference;
    }

    /**
     * Setter for <code>car_dealership.inventory_movements.reference</code>.
     */
    public InventoryMovements setReference(String reference) {
        this.reference = reference;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final InventoryMovements other = (InventoryMovements) obj;
        if (this.movementId == null) {
            if (other.movementId != null)
                return false;
        }
        else if (!this.movementId.equals(other.movementId))
            return false;
        if (this.vehicleId == null) {
            if (other.vehicleId != null)
                return false;
        }
        else if (!this.vehicleId.equals(other.vehicleId))
            return false;
        if (this.movementType == null) {
            if (other.movementType != null)
                return false;
        }
        else if (!this.movementType.equals(other.movementType))
            return false;
        if (this.quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!this.quantity.equals(other.quantity))
            return false;
        if (this.movedAt == null) {
            if (other.movedAt != null)
                return false;
        }
        else if (!this.movedAt.equals(other.movedAt))
            return false;
        if (this.reference == null) {
            if (other.reference != null)
                return false;
        }
        else if (!this.reference.equals(other.reference))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.movementId == null) ? 0 : this.movementId.hashCode());
        result = prime * result + ((this.vehicleId == null) ? 0 : this.vehicleId.hashCode());
        result = prime * result + ((this.movementType == null) ? 0 : this.movementType.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.movedAt == null) ? 0 : this.movedAt.hashCode());
        result = prime * result + ((this.reference == null) ? 0 : this.reference.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InventoryMovements (");

        sb.append(movementId);
        sb.append(", ").append(vehicleId);
        sb.append(", ").append(movementType);
        sb.append(", ").append(quantity);
        sb.append(", ").append(movedAt);
        sb.append(", ").append(reference);

        sb.append(")");
        return sb.toString();
    }
}
