/*
 * This file is generated by jOOQ.
 */
package com.cardealership.cardealership.models;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Invoices implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long invoiceId;
    private Long salesOrderId;
    private String invoiceNumber;
    private OffsetDateTime issuedAt;
    private OffsetDateTime dueAt;
    private BigDecimal totalAmount;
    private String status;

    public Invoices() {}

    public Invoices(Invoices value) {
        this.invoiceId = value.invoiceId;
        this.salesOrderId = value.salesOrderId;
        this.invoiceNumber = value.invoiceNumber;
        this.issuedAt = value.issuedAt;
        this.dueAt = value.dueAt;
        this.totalAmount = value.totalAmount;
        this.status = value.status;
    }

    public Invoices(
        Long invoiceId,
        Long salesOrderId,
        String invoiceNumber,
        OffsetDateTime issuedAt,
        OffsetDateTime dueAt,
        BigDecimal totalAmount,
        String status
    ) {
        this.invoiceId = invoiceId;
        this.salesOrderId = salesOrderId;
        this.invoiceNumber = invoiceNumber;
        this.issuedAt = issuedAt;
        this.dueAt = dueAt;
        this.totalAmount = totalAmount;
        this.status = status;
    }

    /**
     * Getter for <code>car_dealership.invoices.invoice_id</code>.
     */
    public Long getInvoiceId() {
        return this.invoiceId;
    }

    /**
     * Setter for <code>car_dealership.invoices.invoice_id</code>.
     */
    public Invoices setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
        return this;
    }

    /**
     * Getter for <code>car_dealership.invoices.sales_order_id</code>.
     */
    public Long getSalesOrderId() {
        return this.salesOrderId;
    }

    /**
     * Setter for <code>car_dealership.invoices.sales_order_id</code>.
     */
    public Invoices setSalesOrderId(Long salesOrderId) {
        this.salesOrderId = salesOrderId;
        return this;
    }

    /**
     * Getter for <code>car_dealership.invoices.invoice_number</code>.
     */
    public String getInvoiceNumber() {
        return this.invoiceNumber;
    }

    /**
     * Setter for <code>car_dealership.invoices.invoice_number</code>.
     */
    public Invoices setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
        return this;
    }

    /**
     * Getter for <code>car_dealership.invoices.issued_at</code>.
     */
    public OffsetDateTime getIssuedAt() {
        return this.issuedAt;
    }

    /**
     * Setter for <code>car_dealership.invoices.issued_at</code>.
     */
    public Invoices setIssuedAt(OffsetDateTime issuedAt) {
        this.issuedAt = issuedAt;
        return this;
    }

    /**
     * Getter for <code>car_dealership.invoices.due_at</code>.
     */
    public OffsetDateTime getDueAt() {
        return this.dueAt;
    }

    /**
     * Setter for <code>car_dealership.invoices.due_at</code>.
     */
    public Invoices setDueAt(OffsetDateTime dueAt) {
        this.dueAt = dueAt;
        return this;
    }

    /**
     * Getter for <code>car_dealership.invoices.total_amount</code>.
     */
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    /**
     * Setter for <code>car_dealership.invoices.total_amount</code>.
     */
    public Invoices setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
        return this;
    }

    /**
     * Getter for <code>car_dealership.invoices.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>car_dealership.invoices.status</code>.
     */
    public Invoices setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Invoices other = (Invoices) obj;
        if (this.invoiceId == null) {
            if (other.invoiceId != null)
                return false;
        }
        else if (!this.invoiceId.equals(other.invoiceId))
            return false;
        if (this.salesOrderId == null) {
            if (other.salesOrderId != null)
                return false;
        }
        else if (!this.salesOrderId.equals(other.salesOrderId))
            return false;
        if (this.invoiceNumber == null) {
            if (other.invoiceNumber != null)
                return false;
        }
        else if (!this.invoiceNumber.equals(other.invoiceNumber))
            return false;
        if (this.issuedAt == null) {
            if (other.issuedAt != null)
                return false;
        }
        else if (!this.issuedAt.equals(other.issuedAt))
            return false;
        if (this.dueAt == null) {
            if (other.dueAt != null)
                return false;
        }
        else if (!this.dueAt.equals(other.dueAt))
            return false;
        if (this.totalAmount == null) {
            if (other.totalAmount != null)
                return false;
        }
        else if (!this.totalAmount.equals(other.totalAmount))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.invoiceId == null) ? 0 : this.invoiceId.hashCode());
        result = prime * result + ((this.salesOrderId == null) ? 0 : this.salesOrderId.hashCode());
        result = prime * result + ((this.invoiceNumber == null) ? 0 : this.invoiceNumber.hashCode());
        result = prime * result + ((this.issuedAt == null) ? 0 : this.issuedAt.hashCode());
        result = prime * result + ((this.dueAt == null) ? 0 : this.dueAt.hashCode());
        result = prime * result + ((this.totalAmount == null) ? 0 : this.totalAmount.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Invoices (");

        sb.append(invoiceId);
        sb.append(", ").append(salesOrderId);
        sb.append(", ").append(invoiceNumber);
        sb.append(", ").append(issuedAt);
        sb.append(", ").append(dueAt);
        sb.append(", ").append(totalAmount);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
