/*
 * This file is generated by jOOQ.
 */
package com.cardealership.cardealership.models;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lenders implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long lenderId;
    private String name;
    private String phone;
    private String email;
    private String contactName;

    public Lenders() {}

    public Lenders(Lenders value) {
        this.lenderId = value.lenderId;
        this.name = value.name;
        this.phone = value.phone;
        this.email = value.email;
        this.contactName = value.contactName;
    }

    public Lenders(
        Long lenderId,
        String name,
        String phone,
        String email,
        String contactName
    ) {
        this.lenderId = lenderId;
        this.name = name;
        this.phone = phone;
        this.email = email;
        this.contactName = contactName;
    }

    /**
     * Getter for <code>car_dealership.lenders.lender_id</code>.
     */
    public Long getLenderId() {
        return this.lenderId;
    }

    /**
     * Setter for <code>car_dealership.lenders.lender_id</code>.
     */
    public Lenders setLenderId(Long lenderId) {
        this.lenderId = lenderId;
        return this;
    }

    /**
     * Getter for <code>car_dealership.lenders.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>car_dealership.lenders.name</code>.
     */
    public Lenders setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>car_dealership.lenders.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>car_dealership.lenders.phone</code>.
     */
    public Lenders setPhone(String phone) {
        this.phone = phone;
        return this;
    }

    /**
     * Getter for <code>car_dealership.lenders.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>car_dealership.lenders.email</code>.
     */
    public Lenders setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>car_dealership.lenders.contact_name</code>.
     */
    public String getContactName() {
        return this.contactName;
    }

    /**
     * Setter for <code>car_dealership.lenders.contact_name</code>.
     */
    public Lenders setContactName(String contactName) {
        this.contactName = contactName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Lenders other = (Lenders) obj;
        if (this.lenderId == null) {
            if (other.lenderId != null)
                return false;
        }
        else if (!this.lenderId.equals(other.lenderId))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.phone == null) {
            if (other.phone != null)
                return false;
        }
        else if (!this.phone.equals(other.phone))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.contactName == null) {
            if (other.contactName != null)
                return false;
        }
        else if (!this.contactName.equals(other.contactName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.lenderId == null) ? 0 : this.lenderId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.phone == null) ? 0 : this.phone.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.contactName == null) ? 0 : this.contactName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Lenders (");

        sb.append(lenderId);
        sb.append(", ").append(name);
        sb.append(", ").append(phone);
        sb.append(", ").append(email);
        sb.append(", ").append(contactName);

        sb.append(")");
        return sb.toString();
    }
}
